export const SET_MY_UNDERLINES = "SET_MY_UNDERLINES";
export const SET_UNDERLINE = "SET_UNDERLINE";
export const SELECT_BOOK = "SELECT_BOOK";
export const ADD_UNDERLINE = "ADD_UNDERLINE";
export const REMOVE_LINE = "REMOVE_LINE";
