export const SET_MY_UNDERLINES = "SET_MY_UNDERLINES";
export const SELECT_BOOK = "SELECT_BOOK";
export const ADD_UNDERLINE = "ADD_UNDERLINE";
export const REMOVE_LINE = "REMOVE_LINE";
export const TOGGLE_IS_WRITING_LINE = "TOGGLE_IS_WRITING_LINE";
export const TOGGLE_IS_SEARCHING = "TOGGLE_IS_SEARCHING";
